### ISSUE TITLE
Gmail password is visible to the public

### ISSUE THREAD

**Issue by abe-101** [Nevish-302/SeenIt#1]
It isn't good practice to put the username and password in the (public) app code.
a good alternative is to use environment variables.
As an example
```
app = Flask(__name__)
app.config["MAIL_PASSWORD"] = os.getenv("MAIL_PASSWORD")
app.config["MAIL_PORT"] = 465
app.config["MAIL_SERVER"] = "smtp.gmail.com"
app.config["MAIL_USE_SSL"] = True
app.config["MAIL_USERNAME"] = os.getenv("MAIL_USERNAME")
app.config['MAIL_DEFAULT_SENDER'] = (app.config['MAIL_USERNAME'])
mail = Mail(app)
```

You can then set the values for MAIL_PASSWORD and MAIL_USERNAME environment variables every time run script, using

    In Linux: export MAIL_PASSWORD="{your_mail_password}"
                   export MAIL_USERNAME="{your_mail_username}"
    In Windows: set MAIL_PASSWORD="{your_mail_password}"
                         set MAIL_USERNAME="{your_mail_username}"

This way avoids having plain text in file to store password

**Comment by Nevish-302** [comment]
The issue has been resolved. Thanks for the help.

**Comment by abe-101** [comment]
Great! I suggest you now change the password to the account as it is still visible in the git history.
